# Install numcodecs from conda-forge since pip only has source, which resulted in blosc not being installed
# See https://github.com/zarr-developers/numcodecs/issues/69
# Install our own version of scanpy that has dask support, and anndata that has zarr support
worker:
  replicas: 5
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numpy numcodecs -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: gcsfs zarr git+https://github.com/tomwhite/scanpy@dask-1.2.2 git+https://github.com/tomwhite/anndata@zarr urllib3

# We want to keep the same packages on the worker and jupyter environments
jupyter:
  enabled: true
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numpy numcodecs -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: gcsfs zarr git+https://github.com/tomwhite/scanpy@dask-1.2.2 git+https://github.com/tomwhite/anndata@zarr urllib3